services:
  # Django web application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python subscription_billing/manage.py migrate &&
             python subscription_billing/manage.py seed_plans &&
             python subscription_billing/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=subscription_billing.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - CELERY_BROKER_URL=redis://redis:6380/0
      - CELERY_RESULT_BACKEND=django-db

  # PostgreSQL database
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"

  # Redis for Celery broker
  redis:
    image: redis:alpine
    command: redis-server --port 6380
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data

  # Celery worker
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "cd subscription_billing && 
             celery -A subscription_billing worker -l info"
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
      - db
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=subscription_billing.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - CELERY_BROKER_URL=redis://redis:6380/0
      - CELERY_RESULT_BACKEND=django-db

  # Celery beat for scheduled tasks
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "cd subscription_billing && 
             celery -A subscription_billing beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
      - db
      - celery-worker
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=subscription_billing.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - CELERY_BROKER_URL=redis://redis:6380/0
      - CELERY_RESULT_BACKEND=django-db


volumes:
  postgres_data:
  redis_data:

