# Generated by Django 5.2.1 on 2025-05-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for invoice notifications', max_length=254, null=True),
        ),
    ]
