# Generated by Django 5.2.1 on 2025-05-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for subscription notifications', max_length=254, null=True),
        ),
    ]
